package challenge.eda

enum class Topics {
    ORDER_CREATED,
    ORDER_ITEM_PHYSICAL_CREATED,
    ORDER_ITEM_BOOK_CREATED,
    ORDER_ITEM_DIGITAL_CREATED,
    ORDER_ITEM_MEMBERSHIP_CREATED,
    EMAIL_NOTIFICATION_CREATED
}
